Repository eygraber/portal, pull requests merged in 2022-12, with the labels that each got.

#251 Fix for Enter/Exit Transition Issues
  portal-compose/src/commonMain/kotlin/com/eygraber/portal/compose/ComposePortalManager.kt
  portal/src/commonMain/kotlin/com/eygraber/portal/PortalManager.kt
  portal/src/commonMain/kotlin/com/eygraber/portal/internal/PortalEntryBuilder.kt
Labels: bug

#252 Update Kotlin to 1.7.21
  .idea/codeStyles/Project.xml
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/portal-compose-jetbrains.gradle.kts
  build-logic/src/main/kotlin/portal-kotlin-multiplatform.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  samples/simple-portal/android-app/build.gradle.kts
Labels: dependencies

#253 Enable js for multiplatform builds
  .github/workflows/PR.yml
  build-logic/src/main/kotlin/com/eygraber/portal/gradle/kmp.kt
  build-logic/src/main/kotlin/portal-compose-jetbrains.gradle.kts
  build.gradle.kts
  gradle.properties
  kotlin-js-store/yarn.lock
  portal/src/commonTest/kotlin/com/eygraber/portal/PortalSizeTest.kt
  samples/simple-portal/js-app/.gitignore
  samples/simple-portal/js-app/build.gradle.kts
  samples/simple-portal/js-app/src/jsMain/kotlin/main.js.kt
  samples/simple-portal/js-app/src/jsMain/resources/index.html
  samples/simple-portal/js-app/src/jsMain/resources/styles.css
  settings.gradle.kts
Labels: feature

#256 We don't need detekt w/o type resolution
  .github/workflows/PR.yml
  detekt
Labels: chore

#268 Fix version bump when releasing
  .github/workflows/PublishRelease.yml
  README.md
  gradle.properties
Labels: chore
